// Generated by scripts/build_desktop.py. Edit desktop/*.mjs.
// Pure controller shared by the installed single-file plugin and Node regressions.
const routeLabel = value => typeof value === 'string' && value.length <= 120 && /^[a-zA-Z0-9_.:/-]+$/.test(value) ? value : null;
const effortValues = ['none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max', 'ultra'];

export function createRouteController(host, publish, {timeoutMs=35000}={}) {
  let disposed=false, generation=0, currentKey=null, pending=null, queued=false;
  const subscriptions=[];
  const timers=new Set();
  let initializing=true;
  const show=(label, detail) => { if (!disposed) publish({label,detail}); };
  const unavailable=() => show('Jev: unavailable','Routing integration could not be verified in this backend.');
  function identity() {
    const state=host.state;
    const owner=state.focusedSessionOwner.get();
    const runtime=state.focusedSessionId.get();
    const stored=state.focusedStoredSessionId.get();
    if (!owner?.connectionId || !owner?.profile) return {key:'unknown',unknown:true};
    return {key:JSON.stringify([owner.connectionId,owner.profile,runtime,stored]),
      owner:{...owner},runtime,stored};
  }

  function renderLegacy(data, captured) {
    if (!data || data.schema_version!==1 || data.session_id!==captured.runtime || data.stored_session_id!==captured.stored || data.selection_api!==1 || data.evidence!=='session_binding') {
      unavailable(); return;
    }
    if (data.scope_supported!==true) {show('Jev: unsupported profile','Automatic routing currently supports the gateway launch profile.'); return;}
    if (data.status==='selecting') {show('Jev: choosing','Selecting this conversation’s model and effort.'); return;}
    if (data.status!=='routed' && data.status!=='unrouted/default') {
      show('Jev: unrecorded','No routing decision recorded for this conversation.'); return;
    }
    const model=routeLabel(data.model), effort=effortValues.includes(data.reasoning_effort) ? data.reasoning_effort : null;
    if (!model) {show('Jev: unavailable','No valid effective model binding available.'); return;}
    const manual=data.owner?.model==='user' || data.owner?.reasoning==='user';
    const suffix=manual ? ' (manual)' : data.status==='unrouted/default' ? ' (default)' : '';
    show(`Jev: ${model}${effort ? ' · '+effort : ''}${suffix}`,
      `Live session binding${manual ? ' with manual override' : ''}. Provider: ${routeLabel(data.provider) || 'unknown'}. Provider execution is not verified by this display.`);
  }
  function renderNative(data, captured) {
    if (!data || data.schema_version!=='hermes.turn_route.binding.v1' || data.session_id!==captured.runtime ||
        data.stored_session_id!==captured.stored || data.evidence!=='session_binding') {
      unavailable(); return;
    }
    if (data.status==='pending') {show('Jev: choosing','Selecting this conversation’s model.'); return;}
    if (data.status==='unrecorded') {show('Jev: unrecorded','This conversation predates durable route bindings.'); return;}
    if (!['default','routed','user'].includes(data.status)) {unavailable(); return;}
    if (data.status!=='user' && (!Array.isArray(data.middleware_plugins) || !data.middleware_plugins.includes('jev-router'))) {
      unavailable(); return;
    }
    const model=routeLabel(data.model), effort=effortValues.includes(data.reasoning_effort) ? data.reasoning_effort : null;
    if (!model) {unavailable(); return;}
    const manual=data.status==='user' || data.owner==='user';
    const suffix=manual ? ' (manual)' : data.status==='default' ? ' (default)' : '';
    show(`Jev: ${model}${effort ? ' · '+effort : ''}${suffix}`,
      `Live session binding${manual ? ' with manual override' : ''}. Provider: ${routeLabel(data.requested_provider) || routeLabel(data.provider) || 'unknown'}. Provider execution is not verified by this display.`);
  }
  function render(data, captured) {
    if (data?.schema_version==='hermes.turn_route.binding.v1') renderNative(data,captured);
    else renderLegacy(data,captured);
  }
  function refresh() {
    if (disposed || initializing) return;
    let captured;
    try {captured=identity();} catch {captured={key:'unknown',unknown:true};}
    if (captured.key!==currentKey) {
      currentKey=captured.key; generation++; pending=null; queued=false;
      if (captured.unknown) unavailable();
      else if (!captured.runtime || !captured.stored) show('Jev: new chat','Awaiting a session. Routing support has not been verified.');
      else show('Jev: checking','Reading this conversation’s routing state.');
    }
    if (captured.unknown || !captured.runtime || !captured.stored) return;
    if (pending!==null) {queued=true; return;}
    const requestGeneration=++generation;
    pending=requestGeneration;
    let expired=false, timeout;
    const deadline=new Promise((_,reject) => {
      timeout=setTimeout(() => {expired=true; reject(new Error('read timeout'));},timeoutMs);
      timers.add(timeout);
    });
    const read=Promise.resolve().then(async () => {
      const routes=await host.profileRoutes();
      if (disposed || expired || requestGeneration!==generation || identity().key!==captured.key) return null;
      const matches=routes.filter(route => route.connectionId===captured.owner.connectionId && route.profile===captured.owner.profile);
      if (matches.length!==1 || !matches[0].targetProfile) throw new Error('unresolved route');
      const params={session_id:captured.runtime,stored_session_id:captured.stored};
      try {
        return await host.requestProfile(matches[0],'session.turn_route.read',params,5000);
      } catch {
        if (disposed || expired || requestGeneration!==generation || identity().key!==captured.key) return null;
        return host.requestProfile(matches[0],'session.runtime_selection',params,5000);
      }
    });
    Promise.race([read,deadline])
      .then(data => {
        if (!disposed && requestGeneration===generation && identity().key===captured.key) render(data,captured);
      }).catch(() => {
        if (!disposed && requestGeneration===generation) unavailable();
      }).finally(() => {clearTimeout(timeout); timers.delete(timeout); if (pending===requestGeneration) {
          pending=null;
          if (queued && !expired && !disposed) {queued=false; refresh();}
        }});
  }
  try {
    for (const name of ['focusedSessionOwner','focusedSessionId','focusedStoredSessionId','connectionId','gateway']) {
      const atom=host.state[name];
      if (name==='gateway' || name==='connectionId') {
        // Invalidate even if the IDs survive a reconnect to a replacement process.
        subscriptions.push(atom.subscribe(() => {currentKey=null; generation++; pending=null; refresh();}));
      } else subscriptions.push(atom.subscribe(refresh));
    }
    initializing=false;
    refresh();
  } catch {
    initializing=false;
    for (const stop of subscriptions.splice(0)) stop();
    unavailable();
  }
  return {refresh, dispose() {disposed=true; generation++; for (const timer of timers) clearTimeout(timer); timers.clear(); for (const stop of subscriptions.splice(0)) stop();}};
}

import { host, Popover, PopoverTrigger, PopoverContent } from '@hermes/plugin-sdk';
import { useEffect, useState } from 'react';
import { jsx, jsxs } from 'react/jsx-runtime';

function RouteIndicator({ctx}) {
  const [value,setValue]=useState({label:'Jev: checking',detail:'Reading routing support.'});
  const [compact,setCompact]=useState(() => ctx.storage.get('compact',false)===true);
  const [controller,setController]=useState(null);
  useEffect(() => {
    const active=createRouteController(host,setValue);
    setController(active);
    // No repair or restart. Poll only while the app is visible, at background priority.
    const cancel=ctx.setInterval(() => {if (document.visibilityState==='visible') active.refresh();},15000);
    const off=ctx.onEvent('session.info',() => active.refresh());
    return () => {cancel(); off(); active.dispose();};
  },[ctx]);
  return jsxs(Popover,{children:[
    jsx(PopoverTrigger,{asChild:true,children:jsx('button',{
      type:'button', 'aria-label':value.label, title:value.label,
      style:{WebkitAppRegion:'no-drag',fontSize:12,maxWidth:360,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',padding:'4px 8px',borderRadius:6},
      children:compact && !value.label.includes('unavailable') && !value.label.includes('unsupported') ? 'Jev' : value.label
    })}),
    jsxs(PopoverContent,{align:'end',style:{fontSize:12,width:300},children:[
      jsx('div',{style:{fontWeight:600,marginBottom:8},children:value.label}),
      jsx('p',{children:value.detail}),
      jsxs('div',{style:{display:'flex',gap:12,marginTop:12},children:[
        jsx('button',{type:'button',onClick:() => {const next=!compact;setCompact(next);ctx.storage.set('compact',next);},children:compact ? 'Show model in title bar' : 'Minimize label'}),
        jsx('button',{type:'button',onClick:() => controller?.refresh(),children:'Refresh'})
      ]})
    ]})
  ]});
}

export default {
  id:'jev-router',name:'Jev routing',defaultEnabled:false,
  register(ctx) {
    ctx.register({id:'route-indicator',area:'titleBar.right',order:40,
      render:() => jsx(RouteIndicator,{ctx})});
  }
};
