"""Concatenate the pure controller and SDK view into one installable ESM file."""
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
target = root / 'jev-router/desktop/plugin.js'
content = '// Generated by scripts/build_desktop.py. Edit desktop/*.mjs.\n' + '\n'.join(
    (root / name).read_text() for name in ('desktop/controller.mjs','desktop/routed-start.mjs','desktop/view.mjs'))
if '--check' in sys.argv:
    if not target.exists() or target.read_text() != content:
        raise SystemExit('Desktop plugin is stale; run scripts/build_desktop.py')
else:
    target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(content)
